/**
 * Longer original input used once the learner reaches B2/C1.
 * These passages are deliberately broader than the learner's favorite tech topics:
 * technical contexts are mixed with organizational, social and analytical consequences.
 */
export type AdvancedInput = {
  readingExtension: string;
  listeningExtension: string;
};

export const advancedInputs: Record<string, AdvancedInput> = {
  "b2-1": {
    readingExtension: `A system diagram can create the illusion that architecture is mainly about boxes and arrows. In practice, the difficult part is explaining why a boundary exists, what information crosses it, and what failure looks like when one component behaves unexpectedly. Consider a service that receives customer requests, validates them, stores transactional data, and publishes events for other services. A superficial explanation names the API gateway, database, queue, and workers. A useful explanation follows the life of one request, identifies which component owns each decision, and distinguishes synchronous dependencies from asynchronous ones.

Architecture also needs to be discussed in terms of constraints. A design that is sensible for ten internal users may be wasteful for a small prototype, while a design that is simple today may become dangerous if it creates one database shared by unrelated domains. There is rarely a single "advanced" architecture that is automatically better. Engineers need to relate complexity to expected scale, team structure, failure tolerance, security requirements, and the cost of operating the system. This is why professional architecture discussions frequently include phrases such as "the tradeoff is," "the component is responsible for," and "if this dependency fails." Those phrases force the speaker to connect structure to consequences rather than merely naming technologies.

A strong explanation should therefore allow a listener to reconstruct the main data flow and understand at least one design decision. If the listener can repeat the component names but cannot explain why the system was built that way, the explanation has provided inventory rather than architecture.`,
    listeningExtension: `When I review a system with another engineer, I usually ask them to trace one request from the edge of the system to the final side effect. That reveals more than asking for a list of services. I want to know where authentication happens, where validation happens, which component owns the source of truth, and what happens if a downstream dependency is unavailable. The answer does not need to defend every choice. In fact, a credible explanation often admits that one decision was made for speed and may need to change later. What matters is that the speaker can connect the current design to its constraints and explain the tradeoff without hiding behind technology names.`
  },
  "b2-2": {
    readingExtension: `Arguments about the future of software work often become weak because they jump directly from a visible capability to a sweeping prediction. If an AI system can generate a function, some people conclude that programming jobs will disappear. Others react by claiming that nothing important will change because software engineering has always required human judgment. Both positions simplify a more complicated process. A job is not one task; it is a bundle of activities that can change at different speeds. Code generation, test creation, documentation, debugging, requirements analysis, communication, security review, and responsibility for production outcomes are not equally easy to automate.

A stronger argument separates substitution from transformation. A tool may replace a portion of routine implementation while increasing the amount of software that organizations attempt to build. It may also shift the valuable skill from producing syntax quickly to defining constraints, evaluating generated work, integrating systems, and understanding users. At the same time, transition costs are real. Entry-level tasks that once allowed junior developers to learn by doing may shrink, which could create a training problem even if total demand remains healthy.

The quality of an argument depends partly on how it treats uncertainty. Evidence from one company or one period should not automatically be generalized to an entire labor market. A careful speaker can still take a position, but should identify the mechanism behind that position, consider a serious counterargument, and state what evidence would change the conclusion. This is more persuasive than sounding completely certain about an outcome that depends on technology, economics, regulation, and organizational behavior.`,
    listeningExtension: `If you ask whether AI will replace software jobs, my first response is that the question is too broad. Some tasks are already becoming faster, but faster task completion does not map neatly onto fewer jobs. Companies may reduce headcount, build more software with the same team, or redirect engineers toward integration and product work. I would be cautious about predictions that rely on a single impressive demo. The more useful question is which responsibilities remain difficult to automate and which new bottlenecks appear when generation becomes cheap. Verification, security, coordination, and deciding what should be built may become more important rather than less important.`
  },
  "b2-3": {
    readingExtension: `Summarizing is not the same as shortening. A weak summary often keeps the original sentence order and removes details until the text becomes shorter. That method can preserve wording while losing the author's structure. A stronger summary first identifies the central claim, then groups supporting ideas by function: evidence, explanation, limitation, consequence, or recommendation. Only after that mental reorganization should the writer choose new language.

Paraphrasing creates a different challenge. Replacing individual words with synonyms can easily distort meaning or produce unnatural English. For example, changing every content word in a technical sentence may make the result less precise than the original. Effective paraphrase changes the grammatical or conceptual framing while preserving the relationships between ideas. A noun-heavy sentence might become a clause; two clauses might be combined; an example might be generalized; or a cause-and-effect relationship might be made explicit.

This skill matters well beyond academic exercises. Developers summarize documentation for teammates, managers compress complex discussions into decisions, and analysts integrate several sources into one explanation. In each case, the audience needs the meaning rather than a disguised copy. A reliable test is to look away from the source and explain the idea from memory. Then return to the source and check whether any qualification, limitation, or important relationship was lost.`,
    listeningExtension: `When people tell me they cannot paraphrase, I often notice that they are staring at the original sentence while trying to change it. That makes the original syntax very difficult to escape. I suggest a three-step process: understand the idea, hide the source, and explain the idea as if the listener had not seen the text. Then compare the result with the source for accuracy. You may discover that your version is simpler, and that is usually fine if the important meaning has survived. The goal is not to prove that you know many synonyms. The goal is to reproduce the idea faithfully in language that belongs to your own explanation.`
  },
  "b2-4": {
    readingExtension: `Register is the set of choices that makes language appropriate for a particular relationship and purpose. The underlying fact may stay constant while wording changes considerably. A teammate might write, "The deploy broke again—I'm checking it now." A client update may need, "The latest deployment introduced an issue affecting login. We have identified the likely cause and are testing a fix." Neither version is automatically more correct. The question is whether the tone gives the audience the right amount of detail, confidence, responsibility, and urgency.

Professional English is sometimes misunderstood as using longer words and more formal grammar. In reality, effective professional communication is often concise. It avoids unnecessary emotional language, separates known facts from assumptions, and makes the next action visible. When a problem is serious, excessive softening can be just as harmful as excessive bluntness. A message that says "there may possibly be a minor issue" when customers cannot access a service can sound evasive. On the other hand, assigning blame before the facts are clear can damage trust.

Advanced users should be able to shift register intentionally. That includes deciding when contractions are natural, when a direct request needs softening, when passive language protects focus rather than hiding responsibility, and when technical detail should be removed for a nontechnical audience. The goal is not to sound formal. The goal is to sound appropriate.`,
    listeningExtension: `Imagine that I need to tell three people about the same production incident. To my teammate, I might say, "Login is failing after the deploy. Can you check the auth logs while I roll back?" To my manager, I would summarize impact, current action, and risk. To a customer, I would avoid internal speculation and focus on what is affected, what we are doing, and when they can expect another update. The facts have not changed. The communication has changed because each audience needs a different level of technical detail and a different relationship to uncertainty.`
  },
  "b2-5": {
    readingExtension: `Listening difficulty at higher levels is not caused only by unknown vocabulary. Learners often know the words on a transcript but fail to recognize them in continuous speech. Function words become weak, consonants link across word boundaries, familiar phrases are reduced, and speakers signal relationships through stress and intonation rather than explicit connectors. A listener who expects every word to sound like a dictionary recording will therefore process natural speech too slowly.

Accent flexibility adds another layer. The goal is not to imitate every accent but to build robust expectations about variation. A vowel may be realized differently, a consonant may be weaker, or rhythm may shift. What remains useful is the ability to combine sound evidence with syntax, context, and meaning. If one word is unclear but the speaker's purpose is obvious, advanced listening continues rather than freezing on the missing word.

Training should alternate intensive and extensive listening. Intensive work selects a short difficult segment, predicts the words, checks the transcript, notices reductions, shadows the rhythm, and listens again. Extensive work requires staying with several minutes of speech without stopping. The first method improves decoding; the second builds tolerance for uncertainty and real-time comprehension. Permanent slow playback weakens that second ability, so reduced speed should be used as a diagnostic tool and then removed.`,
    listeningExtension: `One mistake I made as a learner was replaying every sentence until I could hear every word. It felt productive, but it trained me to expect perfect certainty. Real conversations do not pause while you reconstruct a reduced phrase. Now I prefer to listen once for the speaker's direction, a second time for important details, and only then inspect a difficult ten-second segment. If I use slower playback, I immediately return to normal speed afterward. The objective is not to create an easy recording. It is to make my brain better at handling the original one.`
  },
  "b2-6": {
    readingExtension: `Technical documentation rewards selective reading. A developer who translates every sentence may understand individual statements yet still miss the page's purpose. Before reading closely, identify what kind of document you are looking at: conceptual overview, API reference, migration guide, troubleshooting page, or tutorial. Each genre answers different questions. An API reference is often searched nonlinearly for parameters and return values, while a migration guide should be read for prerequisites, breaking changes, and ordered actions.

Efficient readers also use structure as information. Headings, code blocks, warnings, examples, and repeated terminology reveal which concepts organize the page. Unknown words should not automatically interrupt reading. First ask whether the word prevents the current task. If the objective is to discover which environment variable enables a feature, understanding every paragraph about internal architecture may be unnecessary.

However, speed must not become carelessness. Documentation frequently encodes conditions in small phrases such as "only when," "unless," "deprecated after," or "not supported with." Missing one qualification can create a bug. Advanced technical reading therefore combines fast navigation with slow attention at decision points. After reading, explaining the page in simpler English is a strong comprehension test because it exposes whether the reader understood the relationship between steps rather than merely locating words.`,
    listeningExtension: `When I open documentation, I first decide what question I am trying to answer. If I am debugging, I search for symptoms, constraints, and version information. If I am learning a new library, I start with the conceptual model before reading every option. I also pay special attention to warning words: required, optional, deprecated, only, must, and unless. Those small words often matter more than a long paragraph. Finally, I try to explain the flow aloud. If I cannot say what happens first, what depends on what, and where the common failure is, I probably have not understood the document deeply enough.`
  },
  "b2-7": {
    readingExtension: `A presentation is not simply an essay spoken aloud. Listeners cannot reread a sentence, so the speaker has to make structure audible. A clear opening gives the audience a reason to care and previews the direction. Each section should have one main function, with transitions that tell listeners whether the speaker is adding evidence, changing direction, acknowledging a limitation, or moving to a recommendation.

Questions reveal a different skill from prepared delivery. A presenter may sound fluent during rehearsed slides but lose control when asked to clarify an assumption. Strong Q&A depends on listening to the exact question, buying a small amount of thinking time naturally, answering the core point first, and then adding detail. If the question contains a false assumption, the speaker should correct it diplomatically instead of accepting the framing.

Technical presenters also need audience awareness. An architecture diagram can support an engineering audience but overwhelm a business audience unless the speaker translates components into consequences. Conversely, a specialist audience may distrust a presentation that stays at slogan level. Preparation should therefore include not only what you plan to say but what different listeners are likely to ask. The goal is controlled flexibility: enough structure to remain coherent, but enough language freedom to respond without returning to a memorized script.`,
    listeningExtension: `The hardest part of a presentation is often the thirty seconds after someone asks an unexpected question. I try not to answer while I am still processing it. I might say, "That's an important distinction," or briefly restate the question to confirm it. Then I give the direct answer before the background. If I do not know, I say what I can establish and what I would need to check. That usually sounds more professional than improvising certainty. Good Q&A is not about having every fact in memory; it is about managing the interaction clearly and responsibly.`
  },
  "b2-8": {
    readingExtension: `B2 independence can be observed when a learner stops treating English as a sequence of exercises and starts using it as a working language. That does not mean every sentence is accurate. It means the learner can maintain an intention despite gaps: explain a system, follow a substantial discussion, read a demanding page, ask for clarification, reformulate an idea, and produce organized writing without returning to Thai for every step.

Readiness should therefore be tested through integration. A learner who scores highly on isolated grammar questions but cannot sustain a four-minute explanation has not demonstrated the same ability as someone whose grammar is imperfect but stable enough to communicate complex meaning. Likewise, watching videos comfortably with subtitles does not prove listening independence if normal speech without text collapses.

A meaningful B2 checkpoint introduces some unfamiliar content and follow-up pressure. The learner should be able to distinguish fact from interpretation, make a position clear, summarize information in new words, and adjust when challenged. Persistent basic errors matter if they repeatedly interfere with clarity, but occasional slips are less important than whether the learner can continue, correct or reformulate, and preserve a coherent line of thought.`,
    listeningExtension: `At B2 I would expect you to do more than survive a familiar conversation. You should be able to explain why you made a technical choice, recognize when a speaker is qualifying a claim, and summarize several minutes of English without translating it sentence by sentence. You will still meet unknown words. The test is what you do next. Can you infer enough from context, ask a precise clarification question, or reformulate around the missing word? Independence is not the absence of difficulty. It is the ability to keep functioning when difficulty appears.`
  },
  "c1-1": {
    readingExtension: `Precision at C1 depends as much on controlling certainty as on possessing sophisticated vocabulary. In public discussions about technology, strong claims are often rewarded because they are memorable: an innovation will "transform everything," a new tool has "proven" that a profession is obsolete, or a policy will "inevitably" produce a particular outcome. Such language may be rhetorically effective while being analytically weak. Evidence usually supports a narrower statement than the headline suggests.

Hedging is sometimes described as making language less confident, but that description misses its purpose. Good hedging calibrates a claim to the strength and scope of the available evidence. "This causes" differs from "this appears to contribute to" not because the second speaker lacks courage, but because causation may not have been established. Similarly, "most teams" and "some teams in this sample" make very different commitments. An advanced speaker should be able to choose between them deliberately.

The opposite problem is over-qualification. If every sentence contains perhaps, possibly, arguably, and to some extent, the speaker can sound unwilling to defend any proposition. Nuance requires a stable core claim together with explicit boundaries. One useful structure is to state the strongest conclusion you can justify, then identify the condition under which it holds, the evidence that supports it, and the uncertainty that remains.

This matters in software and AI discussions because observations are often confounded by rapid organizational change. A team may adopt an AI coding tool at the same time as it changes management, reduces scope, hires experienced engineers, or restructures its architecture. A productivity increase observed afterward does not automatically tell us which factor produced the change. A careful argument can still say that the tool probably contributed, while distinguishing that inference from proof.

C1 language therefore involves stance as a relationship between speaker, evidence, and audience. Expressions such as "the available evidence suggests," "there is little reason to assume," and "a plausible interpretation is" should not be inserted as decoration. They should signal exactly how far the speaker is prepared to go.`,
    listeningExtension: `When I hear a confident technology claim, I ask three questions before I decide whether I believe it. First, what exactly is being measured? Second, what alternative explanation could produce the same observation? Third, how far is the speaker generalizing beyond the evidence? Those questions do not force me into a neutral position. I can still conclude that a tool is useful or that a trend is important. But the wording of my conclusion should reflect what I actually know. If the evidence comes from a small group of experienced developers, I should not casually say that the result applies to every programmer. Precision is not weaker communication. In professional settings, it often creates more trust because listeners can see the boundary between evidence, interpretation, and speculation.`
  },
  "c1-2": {
    readingExtension: `Complex arguments are difficult not because they require long sentences but because several legitimate considerations must be held in view at once. Suppose a university considers allowing unrestricted use of generative AI in programming assignments. One argument emphasizes authentic professional practice: graduates will work with AI tools, so banning them may prepare students for an environment that no longer exists. A competing argument focuses on skill formation: if students outsource early problem-solving, they may never develop the mental models needed to judge generated code later.

A weak debate treats these positions as mutually exclusive slogans. A stronger argument asks which learning objective is being assessed. In an introductory course, the ability to reason through a loop or debug a small function may need to be demonstrated without assistance. In a capstone project, evaluating and integrating tools responsibly may itself be part of the objective. The policy could therefore vary by task rather than choosing between total prohibition and unrestricted use.

Counterarguments should also be represented fairly. If you reduce the opposing position to an obviously foolish claim, rebutting it proves little. The intellectually useful version is the strongest plausible objection to your own view. After stating it, you can concede what it gets right, show where its scope is limited, and explain why your conclusion still follows.

Argument architecture helps listeners track this movement. A thesis establishes direction. Supporting lines explain why. A serious counterargument tests the thesis. A concession marks genuine common ground. A response then narrows, modifies, or defends the original position. The conclusion should not simply repeat the introduction; it should reflect what survived the comparison.

At C1, discourse markers such as "while that concern is justified" or "a more significant issue, however" are useful only if the conceptual relationship is real. The structure should exist in the reasoning before it appears in the language.`,
    listeningExtension: `I am less interested in whether a speaker can produce a phrase like "on the other hand" than in whether there is genuinely another hand to consider. In a strong discussion, the counterargument changes the shape of the conclusion. Perhaps the original claim becomes narrower, or a condition is added. That is a sign that the speaker is reasoning rather than delivering a memorized speech. If the opposing view is mentioned for ten seconds and then dismissed without engaging its strongest point, the language may sound advanced while the argument remains simple.`
  },
  "c1-3": {
    readingExtension: `Synthesis begins where summary stops. Imagine two reports about remote work. The first finds that experienced software engineers report higher individual productivity at home, largely because they experience fewer interruptions. The second observes that junior employees in distributed teams ask fewer spontaneous questions and take longer to build informal relationships. A source-by-source summary would describe Report A and then Report B. A synthesis reorganizes the evidence around ideas: individual concentration may improve while some forms of learning and coordination become harder.

This reorganization matters because sources rarely answer exactly the same question. They may use different populations, methods, definitions, or time periods. Treating their results as directly comparable can create false certainty. A careful synthesis identifies where evidence converges, where it appears to conflict, and whether the apparent conflict can be explained by scope. The two remote-work findings above are not necessarily contradictory if one focuses on experienced individual contributors and the other on junior socialization.

The writer also has to maintain ownership of the final structure. Copying the order of the sources can make the synthesis feel like stitched summaries. Instead, decide which conceptual categories answer your question, then place evidence from different sources inside those categories. Transitions should show relationships: corroboration, qualification, methodological difference, or unresolved tension.

At C1, synthesis also involves restraint. If neither source establishes causation, the combined account should not suddenly claim it. If the sources measure productivity differently, that limitation belongs in the explanation. The value added by the writer is not stronger certainty than the evidence allows; it is a clearer map of what the evidence collectively supports.

This skill transfers directly to technical work. Architecture decisions often require combining documentation, benchmarks, incident reports, user constraints, and team experience. A useful briefing does not merely list each input. It explains what the inputs mean together and where uncertainty still affects the decision.`,
    listeningExtension: `When I prepare a briefing from several sources, I avoid writing one paragraph per source. That structure is easy to produce but hard for a listener to use. I first ask what decision or question the briefing is meant to support. Then I create two or three themes and place evidence under them, even if that means moving back and forth between sources. I also mark disagreements explicitly. Sometimes two sources truly conflict; sometimes they are looking at different populations or using different definitions. The synthesis should make that distinction visible rather than hiding it in a smooth paragraph.`
  },
  "c1-4": {
    readingExtension: `Reformulation is a core professional skill because communication rarely succeeds on the first attempt with every audience. Consider the phrase "eventual consistency." An engineer may understand it as a property of distributed data where replicas can temporarily disagree but converge if no new updates occur. A beginner may need a concrete analogy: two screens can show different values for a short time even though the system is designed to make them match later. A manager may care less about the mechanism than the consequence: some users may briefly see stale information, so the product must decide where that delay is acceptable.

These explanations differ in vocabulary and emphasis, but they should preserve the same underlying concept. Oversimplification becomes a problem when adaptation changes the truth. Saying "the databases always sync instantly" would make the beginner explanation easier but incorrect. Conversely, using specialist terminology with a nontechnical audience can be accurate yet ineffective if the listener cannot connect it to a decision.

Advanced reformulation also helps when a speaker gets stuck. Instead of abandoning a message because one precise word is unavailable, the speaker can define the idea, give an example, contrast it with something else, or state the consequence. This keeps interaction moving and reduces the pressure to translate from Thai in search of one perfect word.

Professional precision therefore does not mean using the most technical form available. It means selecting the form that preserves necessary distinctions for the current audience. An expert conversation may require exact terms; an executive summary may require compressed consequences; a user-facing explanation may require an analogy and a warning about what the user will observe.

At C1, the speaker should be able to shift among these versions quickly and explain why the wording changed. That metalinguistic awareness is evidence of flexible control rather than memorized performance.`,
    listeningExtension: `If someone tells me they do not understand my explanation, repeating the same sentence more slowly is rarely enough. I try a different route. I might replace the definition with an example, describe the consequence, or compare the concept with something familiar. The key is to preserve the important boundary. Simplification should remove unnecessary complexity, not remove the condition that makes the statement true. In a technical meeting, that ability saves time because the conversation can continue without forcing every participant to share the same specialist vocabulary.`
  },
  "c1-5": {
    readingExtension: `Much of professional disagreement is indirect. A colleague who says, "I'm not sure we've fully accounted for the migration risk" may be doing more than expressing uncertainty; depending on context and intonation, the comment may function as a serious objection. Similarly, "That's one way of looking at it" can signal polite distance rather than agreement. Literal comprehension captures the words but may miss the social action being performed.

Pragmatic interpretation depends on relationship, setting, shared knowledge, and prosody. The same sentence can sound supportive, skeptical, impatient, or diplomatic. This makes advanced listening difficult because there is not always a single lexical item that announces the speaker's stance. Listeners infer it from what is emphasized, what is omitted, and how the contribution relates to what came before.

Responding appropriately requires equal subtlety. Directly saying "You're wrong" may be efficient in some peer conversations but unnecessarily confrontational in a cross-functional meeting. An alternative such as "I see the advantage, although I'm less convinced about the operational assumption" preserves disagreement while acknowledging common ground. The purpose is not to hide the position. It is to separate critique of an idea from threat to the relationship.

Indirectness can also be abused. Excessive diplomatic language may make decisions ambiguous, especially when safety or responsibility is involved. Advanced users should therefore recognize when clarity needs to override politeness. "I don't think we should deploy this tonight" is more appropriate than an extremely softened hint if the speaker believes deployment creates a serious risk.

C1 pragmatic competence is thus a balancing act: infer more than the literal wording, but avoid imagining hidden meaning without contextual evidence; communicate disagreement clearly, but choose a degree of directness appropriate to the stakes and relationship.`,
    listeningExtension: `In meetings, I pay attention to the difference between agreement with a goal and agreement with a proposal. Someone might say, "I agree that we need to reduce latency," and then spend the next minute questioning the suggested architecture. If I only hear the phrase "I agree," I will misunderstand their position. I also listen for softened objections such as "my concern would be" or "I'm not completely persuaded that." Those expressions often signal real disagreement delivered in a way that keeps collaboration possible.`
  },
  "c1-6": {
    readingExtension: `Senior technical discussions rarely optimize one variable. A team choosing between a managed platform and a self-hosted system may compare cost, performance, portability, security, operational burden, hiring difficulty, failure recovery, and strategic dependence on a vendor. A recommendation that focuses on benchmark speed while ignoring the team's ability to operate the system is incomplete even if the benchmark is accurate.

Business constraints make the discussion more demanding. Suppose a startup expects rapid growth but has only two infrastructure engineers. A self-hosted solution might offer lower marginal cost at scale, yet create operational work that delays product development. A managed service may cost more per unit but reduce staffing risk. Neither answer is universally correct because the decision depends on runway, growth uncertainty, compliance obligations, and how reversible the choice is.

Advanced discussion should distinguish reversible from irreversible decisions. If migration later is relatively cheap, the team can prioritize speed today and gather evidence. If a choice creates deep data lock-in or regulatory exposure, more analysis may be justified. This distinction changes how much certainty is needed before acting.

The speaker should also surface failure modes. What happens if demand doubles? If the vendor changes pricing? If a regional outage occurs? If the model serving cost is three times the estimate? Thinking through these scenarios does not mean predicting the future exactly. It means testing whether the recommendation remains reasonable under plausible variation.

At C1, language enables the reasoning rather than decorating it. Terms such as "from an operational perspective," "the more material risk is," and "the tradeoff comes down to" help organize multiple dimensions. A strong recommendation ends with a choice, the conditions that justify it, the main risk, and the trigger that would cause the team to revisit the decision.`,
    listeningExtension: `When I hear a technology recommendation, I look for the assumption that is doing most of the work. Maybe the recommendation only makes sense if traffic grows ten times, or if the team can hire an experienced operator, or if vendor pricing stays stable. Once that assumption is visible, the discussion becomes more productive. We can ask how likely it is, what evidence we have, and whether the decision is reversible. A professional decision is rarely "this technology is best." It is closer to "given these constraints, this option creates the best balance, and here is what would make us reconsider."`
  },
  "c1-7": {
    readingExtension: `Analytical writing asks the reader to follow an argument that remains coherent across paragraphs, not merely sentence by sentence. A paragraph should usually make a contribution to the larger line of reasoning: establish a claim, present evidence, examine a limitation, compare explanations, or draw an implication. When paragraphs exist only because the writer has reached a certain length, the text may contain advanced vocabulary while lacking architecture.

Nominalization and complex noun phrases can compress information, but they also create risk. "The rapid organizational adoption of automated code-generation systems" packages several relationships into one phrase. Used carefully, this allows efficient reference to a known concept. Used repeatedly, it can produce dense writing in which actors and actions disappear. C1 writers need the freedom to choose between compact noun phrases and explicit clauses based on what the reader needs to process.

Cohesion likewise extends beyond linking words. Repeating key concepts strategically, using reference terms clearly, and maintaining a stable topic progression can connect paragraphs without inserting "moreover" into every transition. Sophisticated cohesion is often quieter than textbook cohesion.

Revision should occur at several levels. First ask whether the thesis actually answers the question. Then test paragraph order: does each section create a reason for the next? After that, inspect evidence and counterargument. Only later should sentence-level editing focus on grammar, collocation, and rhythm. Editing every sentence during drafting can trap a learner in local correctness while the argument remains weak.

A strong C1 text also controls stance. Assertions should be forceful where evidence is strong and qualified where evidence is limited. The writer should distinguish what a source reports, what the writer infers, and what remains speculative. This combination of structure, precision, and epistemic control is more important than displaying rare words.`,
    listeningExtension: `When I revise an analytical essay, I temporarily ignore grammar. I write one short label next to each paragraph: claim, evidence, counterargument, implication, or whatever that paragraph is actually doing. If I cannot label it, the paragraph may not have a clear job. Then I read only the labels. If the argument still makes sense, I know the structure is probably working. After that I return to language. This order matters because polishing a sentence that belongs in the wrong paragraph is wasted effort.`
  },
  "c1-8": {
    readingExtension: `C1 is best treated as a threshold of operational flexibility rather than the end of language learning. A C1 user can engage with demanding material, infer meaning that is not fully explicit, express ideas fluently without constant visible searching, and adapt language to social, academic, and professional purposes. This does not imply native-like performance, perfect grammar, or complete knowledge of every domain. It implies that language limitations rarely force the user to abandon the intended message in ordinary demanding contexts.

An exit assessment should therefore resist overfamiliarity. If every speaking task concerns the learner's favorite programming project, practiced content can hide weak general control. The assessment needs an unfamiliar abstract question, a professional task, technical explanation, sustained listening, demanding reading, synthesis, and writing. Follow-up questions are particularly valuable because they reveal whether a speaker can reformulate when the prepared path no longer fits.

The same principle applies to receptive skills. Understanding a transcript after repeated slow listening is useful training evidence but not equivalent to understanding natural speech in real time. Reading a text after translating every sentence may eventually produce comprehension but does not demonstrate the processing efficiency expected of an advanced independent user. The final gate therefore combines accuracy with speed, inference, and the ability to maintain a coherent mental model over longer input.

Productive performance should be judged for range, precision, organization, interaction, and control. Occasional mistakes are compatible with C1; persistent elementary patterns that repeatedly disrupt clarity are more concerning. Vocabulary should be evaluated by appropriacy and collocation rather than by rarity. Speaking should show the ability to qualify, clarify, concede, disagree diplomatically, and respond to unexpected questions.

Most importantly, completing a curriculum is not itself evidence of C1. The curriculum supplies enough structured practice and progressively difficult tasks to make C1 a realistic target. The level is earned only when independent performance converges across speaking, listening, reading, and writing under a demanding integrated assessment.`,
    listeningExtension: `At the final stage, I would not ask whether you remember every advanced structure we taught. I would ask whether you can use English to keep doing the task when the situation becomes unpredictable. Can you hear a qualified disagreement? Can you explain a difficult idea a second way? Can you read two sources and tell me where they genuinely differ? Can you defend a position while acknowledging the strongest objection? Those behaviors show control. Finishing Day 224 gives you the opportunity to demonstrate them; it does not automatically grant the level.`
  }
};
